title: "[提案]"
body:
  - type: input
    id: package-name
    attributes:
      label: パッケージ名
    validations:
      required: true
  - type: dropdown
    id: safety-status
    attributes:
      label: 安全性の評価
      options:
        - 安全
        - 危険
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: 理由
    validations:
      required: true
